version: "3"

services:
  backend-accounts:
    build:
      context: ./accounts # backend-accounts1 -> backend Service 1
    image: backend-accounts:latest 
    container_name: backend-accounts
    #volumes:
    #  - [ REPLACE this with Backend Service path ]:/app # Like E:\repos\backend-service\build\libs
    ports:
      - 9002:8080 # App access Port, inside container it is 8080 and mappped with 9002
      - 1111:8000 # to remote debug springboot application
   # environment:                                                                      
    #  JAR : [ jar file name - locate form build path ] # Just Jar Name like module-backend-0.0.1-SNAPSHOT.jar
  bank-ui:
    build:
      context: ./bank-ui
    image: bank-ui:latest
    container_name: bank-ui
    #volumes:
    #  - [ path of ui app build ]:/usr/share/nginx/html # We need to Map UI app build path here, Like my angular UI App, E:\repos\ui-app\dist\ui-app 
     # - bank-ui\ngnix.conf:/etc/nginx/conf.d/
    depends_on:
      - backend-accounts
    ports:
      - 80:80